// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calc_mu2t_mv
arma::vec calc_mu2t_mv(List mdl, double rho, List ltmt, arma::vec hv);
RcppExport SEXP _MSTest_calc_mu2t_mv(SEXP mdlSEXP, SEXP rhoSEXP, SEXP ltmtSEXP, SEXP hvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< List >::type ltmt(ltmtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hv(hvSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mu2t_mv(mdl, rho, ltmt, hv));
    return rcpp_result_gen;
END_RCPP
}
// calc_mu2t
arma::vec calc_mu2t(List mdl, double rho, List ltmt);
RcppExport SEXP _MSTest_calc_mu2t(SEXP mdlSEXP, SEXP rhoSEXP, SEXP ltmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< List >::type ltmt(ltmtSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mu2t(mdl, rho, ltmt));
    return rcpp_result_gen;
END_RCPP
}
// chpStat
arma::vec chpStat(List mdl, double rho_b, List ltmt, int var_switch);
RcppExport SEXP _MSTest_chpStat(SEXP mdlSEXP, SEXP rho_bSEXP, SEXP ltmtSEXP, SEXP var_switchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< double >::type rho_b(rho_bSEXP);
    Rcpp::traits::input_parameter< List >::type ltmt(ltmtSEXP);
    Rcpp::traits::input_parameter< int >::type var_switch(var_switchSEXP);
    rcpp_result_gen = Rcpp::wrap(chpStat(mdl, rho_b, ltmt, var_switch));
    return rcpp_result_gen;
END_RCPP
}
// bootCV
arma::mat bootCV(List mdl, double rho_b, int N, int var_switch);
RcppExport SEXP _MSTest_bootCV(SEXP mdlSEXP, SEXP rho_bSEXP, SEXP NSEXP, SEXP var_switchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< double >::type rho_b(rho_bSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type var_switch(var_switchSEXP);
    rcpp_result_gen = Rcpp::wrap(bootCV(mdl, rho_b, N, var_switch));
    return rcpp_result_gen;
END_RCPP
}
// CHPadist
arma::mat CHPadist(int itn, int tr, double rho_b);
RcppExport SEXP _MSTest_CHPadist(SEXP itnSEXP, SEXP trSEXP, SEXP rho_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type itn(itnSEXP);
    Rcpp::traits::input_parameter< int >::type tr(trSEXP);
    Rcpp::traits::input_parameter< double >::type rho_b(rho_bSEXP);
    rcpp_result_gen = Rcpp::wrap(CHPadist(itn, tr, rho_b));
    return rcpp_result_gen;
END_RCPP
}
// calc_moments
arma::vec calc_moments(arma::vec ehat);
RcppExport SEXP _MSTest_calc_moments(SEXP ehatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type ehat(ehatSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_moments(ehat));
    return rcpp_result_gen;
END_RCPP
}
// sim_moments
arma::mat sim_moments(int t, int totsim);
RcppExport SEXP _MSTest_sim_moments(SEXP tSEXP, SEXP totsimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type totsim(totsimSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_moments(t, totsim));
    return rcpp_result_gen;
END_RCPP
}
// combine_stat
arma::vec combine_stat(arma::vec s0, arma::mat sN, arma::mat params, int N, std::string type);
RcppExport SEXP _MSTest_combine_stat(SEXP s0SEXP, SEXP sNSEXP, SEXP paramsSEXP, SEXP NSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type s0(s0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sN(sNSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(combine_stat(s0, sN, params, N, type));
    return rcpp_result_gen;
END_RCPP
}
// calc_mcstat
arma::mat calc_mcstat(arma::vec ezt, int N, arma::mat params);
RcppExport SEXP _MSTest_calc_mcstat(SEXP eztSEXP, SEXP NSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type ezt(eztSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mcstat(ezt, N, params));
    return rcpp_result_gen;
END_RCPP
}
// approx_dist_loop
arma::mat approx_dist_loop(arma::mat SN2);
RcppExport SEXP _MSTest_approx_dist_loop(SEXP SN2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type SN2(SN2SEXP);
    rcpp_result_gen = Rcpp::wrap(approx_dist_loop(SN2));
    return rcpp_result_gen;
END_RCPP
}
// grid_eval
arma::mat grid_eval(arma::vec y, arma::mat x, arma::mat mcgrid, int N, arma::mat params);
RcppExport SEXP _MSTest_grid_eval(SEXP ySEXP, SEXP xSEXP, SEXP mcgridSEXP, SEXP NSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mcgrid(mcgridSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_eval(y, x, mcgrid, N, params));
    return rcpp_result_gen;
END_RCPP
}
// transMat_cpp
arma::mat transMat_cpp(arma::vec ind, int k);
RcppExport SEXP _MSTest_transMat_cpp(SEXP indSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type ind(indSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(transMat_cpp(ind, k));
    return rcpp_result_gen;
END_RCPP
}
// randInitVal_cpp
List randInitVal_cpp(List mdl, int k);
RcppExport SEXP _MSTest_randInitVal_cpp(SEXP mdlSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(randInitVal_cpp(mdl, k));
    return rcpp_result_gen;
END_RCPP
}
// ms_logLikel_cpp
List ms_logLikel_cpp(arma::vec th, arma::vec y, arma::mat X, arma::mat MScoef);
RcppExport SEXP _MSTest_ms_logLikel_cpp(SEXP thSEXP, SEXP ySEXP, SEXP XSEXP, SEXP MScoefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type th(thSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type MScoef(MScoefSEXP);
    rcpp_result_gen = Rcpp::wrap(ms_logLikel_cpp(th, y, X, MScoef));
    return rcpp_result_gen;
END_RCPP
}
// EM_hamilton_cpp
List EM_hamilton_cpp(arma::vec th, arma::vec y, arma::mat X, arma::mat MScoef, long double vof);
RcppExport SEXP _MSTest_EM_hamilton_cpp(SEXP thSEXP, SEXP ySEXP, SEXP XSEXP, SEXP MScoefSEXP, SEXP vofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type th(thSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type MScoef(MScoefSEXP);
    Rcpp::traits::input_parameter< long double >::type vof(vofSEXP);
    rcpp_result_gen = Rcpp::wrap(EM_hamilton_cpp(th, y, X, MScoef, vof));
    return rcpp_result_gen;
END_RCPP
}
// msmdl_cpp
List msmdl_cpp(List mdl, int k, String method, int mxit);
RcppExport SEXP _MSTest_msmdl_cpp(SEXP mdlSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP mxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type mxit(mxitSEXP);
    rcpp_result_gen = Rcpp::wrap(msmdl_cpp(mdl, k, method, mxit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MSTest_calc_mu2t_mv", (DL_FUNC) &_MSTest_calc_mu2t_mv, 4},
    {"_MSTest_calc_mu2t", (DL_FUNC) &_MSTest_calc_mu2t, 3},
    {"_MSTest_chpStat", (DL_FUNC) &_MSTest_chpStat, 4},
    {"_MSTest_bootCV", (DL_FUNC) &_MSTest_bootCV, 4},
    {"_MSTest_CHPadist", (DL_FUNC) &_MSTest_CHPadist, 3},
    {"_MSTest_calc_moments", (DL_FUNC) &_MSTest_calc_moments, 1},
    {"_MSTest_sim_moments", (DL_FUNC) &_MSTest_sim_moments, 2},
    {"_MSTest_combine_stat", (DL_FUNC) &_MSTest_combine_stat, 5},
    {"_MSTest_calc_mcstat", (DL_FUNC) &_MSTest_calc_mcstat, 3},
    {"_MSTest_approx_dist_loop", (DL_FUNC) &_MSTest_approx_dist_loop, 1},
    {"_MSTest_grid_eval", (DL_FUNC) &_MSTest_grid_eval, 5},
    {"_MSTest_transMat_cpp", (DL_FUNC) &_MSTest_transMat_cpp, 2},
    {"_MSTest_randInitVal_cpp", (DL_FUNC) &_MSTest_randInitVal_cpp, 2},
    {"_MSTest_ms_logLikel_cpp", (DL_FUNC) &_MSTest_ms_logLikel_cpp, 4},
    {"_MSTest_EM_hamilton_cpp", (DL_FUNC) &_MSTest_EM_hamilton_cpp, 5},
    {"_MSTest_msmdl_cpp", (DL_FUNC) &_MSTest_msmdl_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_MSTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
