// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cov2corr
arma::mat cov2corr(arma::mat cov_mat);
RcppExport SEXP _MSTest_cov2corr(SEXP cov_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type cov_mat(cov_matSEXP);
    rcpp_result_gen = Rcpp::wrap(cov2corr(cov_mat));
    return rcpp_result_gen;
END_RCPP
}
// covar_vech
arma::vec covar_vech(arma::mat mat);
RcppExport SEXP _MSTest_covar_vech(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(covar_vech(mat));
    return rcpp_result_gen;
END_RCPP
}
// covar_unvech
arma::mat covar_unvech(arma::vec sig, int n);
RcppExport SEXP _MSTest_covar_unvech(SEXP sigSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(covar_unvech(sig, n));
    return rcpp_result_gen;
END_RCPP
}
// logLike_AR
double logLike_AR(arma::vec theta, List mdl);
RcppExport SEXP _MSTest_logLike_AR(SEXP thetaSEXP, SEXP mdlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    rcpp_result_gen = Rcpp::wrap(logLike_AR(theta, mdl));
    return rcpp_result_gen;
END_RCPP
}
// logLike_VAR
double logLike_VAR(arma::vec theta, List mdl);
RcppExport SEXP _MSTest_logLike_VAR(SEXP thetaSEXP, SEXP mdlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    rcpp_result_gen = Rcpp::wrap(logLike_VAR(theta, mdl));
    return rcpp_result_gen;
END_RCPP
}
// randP
arma::mat randP(int k);
RcppExport SEXP _MSTest_randP(SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(randP(k));
    return rcpp_result_gen;
END_RCPP
}
// limP
arma::vec limP(arma::mat P);
RcppExport SEXP _MSTest_limP(SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(limP(P));
    return rcpp_result_gen;
END_RCPP
}
// ts_lagged
List ts_lagged(arma::mat Y, int ar);
RcppExport SEXP _MSTest_ts_lagged(SEXP YSEXP, SEXP arSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type ar(arSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_lagged(Y, ar));
    return rcpp_result_gen;
END_RCPP
}
// paramListMS
List paramListMS(arma::vec theta, int ar, int k, bool msmu, bool msvar);
RcppExport SEXP _MSTest_paramListMS(SEXP thetaSEXP, SEXP arSEXP, SEXP kSEXP, SEXP msmuSEXP, SEXP msvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type ar(arSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type msmu(msmuSEXP);
    Rcpp::traits::input_parameter< bool >::type msvar(msvarSEXP);
    rcpp_result_gen = Rcpp::wrap(paramListMS(theta, ar, k, msmu, msvar));
    return rcpp_result_gen;
END_RCPP
}
// paramListMSVAR
List paramListMSVAR(arma::vec theta, int q, int ar, int k, bool msmu, bool msvar);
RcppExport SEXP _MSTest_paramListMSVAR(SEXP thetaSEXP, SEXP qSEXP, SEXP arSEXP, SEXP kSEXP, SEXP msmuSEXP, SEXP msvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type ar(arSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type msmu(msmuSEXP);
    Rcpp::traits::input_parameter< bool >::type msvar(msvarSEXP);
    rcpp_result_gen = Rcpp::wrap(paramListMSVAR(theta, q, ar, k, msmu, msvar));
    return rcpp_result_gen;
END_RCPP
}
// calcMSResid
arma::mat calcMSResid(List mdl, arma::mat mu, int k);
RcppExport SEXP _MSTest_calcMSResid(SEXP mdlSEXP, SEXP muSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(calcMSResid(mdl, mu, k));
    return rcpp_result_gen;
END_RCPP
}
// calcMSVARResid
List calcMSVARResid(List mdl, List mu, int k);
RcppExport SEXP _MSTest_calcMSVARResid(SEXP mdlSEXP, SEXP muSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< List >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(calcMSVARResid(mdl, mu, k));
    return rcpp_result_gen;
END_RCPP
}
// initValsMS
arma::vec initValsMS(List mdl, int k);
RcppExport SEXP _MSTest_initValsMS(SEXP mdlSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(initValsMS(mdl, k));
    return rcpp_result_gen;
END_RCPP
}
// initValsMSVAR
arma::vec initValsMSVAR(List mdl, int k);
RcppExport SEXP _MSTest_initValsMSVAR(SEXP mdlSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(initValsMSVAR(mdl, k));
    return rcpp_result_gen;
END_RCPP
}
// MCpval
double MCpval(double test_stat, arma::vec null_vec, Rcpp::String type);
RcppExport SEXP _MSTest_MCpval(SEXP test_statSEXP, SEXP null_vecSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type test_stat(test_statSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type null_vec(null_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(MCpval(test_stat, null_vec, type));
    return rcpp_result_gen;
END_RCPP
}
// simuAR
List simuAR(List mdl_h0, int burnin);
RcppExport SEXP _MSTest_simuAR(SEXP mdl_h0SEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl_h0(mdl_h0SEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(simuAR(mdl_h0, burnin));
    return rcpp_result_gen;
END_RCPP
}
// simuMSAR
List simuMSAR(List mdl_h0, int burnin);
RcppExport SEXP _MSTest_simuMSAR(SEXP mdl_h0SEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl_h0(mdl_h0SEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(simuMSAR(mdl_h0, burnin));
    return rcpp_result_gen;
END_RCPP
}
// simuVAR
List simuVAR(List mdl_h0, int burnin);
RcppExport SEXP _MSTest_simuVAR(SEXP mdl_h0SEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl_h0(mdl_h0SEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(simuVAR(mdl_h0, burnin));
    return rcpp_result_gen;
END_RCPP
}
// simuMSVAR
List simuMSVAR(List mdl_h0, int burnin);
RcppExport SEXP _MSTest_simuMSVAR(SEXP mdl_h0SEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl_h0(mdl_h0SEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(simuMSVAR(mdl_h0, burnin));
    return rcpp_result_gen;
END_RCPP
}
// simuNorm
List simuNorm(List mdl_h0);
RcppExport SEXP _MSTest_simuNorm(SEXP mdl_h0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl_h0(mdl_h0SEXP);
    rcpp_result_gen = Rcpp::wrap(simuNorm(mdl_h0));
    return rcpp_result_gen;
END_RCPP
}
// simuHMM
List simuHMM(List mdl_h0, int burnin);
RcppExport SEXP _MSTest_simuHMM(SEXP mdl_h0SEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl_h0(mdl_h0SEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(simuHMM(mdl_h0, burnin));
    return rcpp_result_gen;
END_RCPP
}
// calc_mu2t_mv
arma::vec calc_mu2t_mv(List mdl, double rho, List ltmt, arma::vec hv);
RcppExport SEXP _MSTest_calc_mu2t_mv(SEXP mdlSEXP, SEXP rhoSEXP, SEXP ltmtSEXP, SEXP hvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< List >::type ltmt(ltmtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hv(hvSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mu2t_mv(mdl, rho, ltmt, hv));
    return rcpp_result_gen;
END_RCPP
}
// calc_mu2t
arma::vec calc_mu2t(List mdl, double rho, List ltmt);
RcppExport SEXP _MSTest_calc_mu2t(SEXP mdlSEXP, SEXP rhoSEXP, SEXP ltmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< List >::type ltmt(ltmtSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mu2t(mdl, rho, ltmt));
    return rcpp_result_gen;
END_RCPP
}
// chpStat
arma::vec chpStat(List mdl, double rho_b, List ltmt, int var_switch);
RcppExport SEXP _MSTest_chpStat(SEXP mdlSEXP, SEXP rho_bSEXP, SEXP ltmtSEXP, SEXP var_switchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< double >::type rho_b(rho_bSEXP);
    Rcpp::traits::input_parameter< List >::type ltmt(ltmtSEXP);
    Rcpp::traits::input_parameter< int >::type var_switch(var_switchSEXP);
    rcpp_result_gen = Rcpp::wrap(chpStat(mdl, rho_b, ltmt, var_switch));
    return rcpp_result_gen;
END_RCPP
}
// bootCV
arma::mat bootCV(List mdl, double rho_b, int N, int var_switch);
RcppExport SEXP _MSTest_bootCV(SEXP mdlSEXP, SEXP rho_bSEXP, SEXP NSEXP, SEXP var_switchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< double >::type rho_b(rho_bSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type var_switch(var_switchSEXP);
    rcpp_result_gen = Rcpp::wrap(bootCV(mdl, rho_b, N, var_switch));
    return rcpp_result_gen;
END_RCPP
}
// LR_samp_dist
arma::vec LR_samp_dist(List mdl_h0, int k1, bool msmu, bool msvar, int N, int maxit, double thtol, int burnin, int max_init, int dist_converge_iter, int init_val_try_dist);
RcppExport SEXP _MSTest_LR_samp_dist(SEXP mdl_h0SEXP, SEXP k1SEXP, SEXP msmuSEXP, SEXP msvarSEXP, SEXP NSEXP, SEXP maxitSEXP, SEXP thtolSEXP, SEXP burninSEXP, SEXP max_initSEXP, SEXP dist_converge_iterSEXP, SEXP init_val_try_distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl_h0(mdl_h0SEXP);
    Rcpp::traits::input_parameter< int >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< bool >::type msmu(msmuSEXP);
    Rcpp::traits::input_parameter< bool >::type msvar(msvarSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type thtol(thtolSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type max_init(max_initSEXP);
    Rcpp::traits::input_parameter< int >::type dist_converge_iter(dist_converge_iterSEXP);
    Rcpp::traits::input_parameter< int >::type init_val_try_dist(init_val_try_distSEXP);
    rcpp_result_gen = Rcpp::wrap(LR_samp_dist(mdl_h0, k1, msmu, msvar, N, maxit, thtol, burnin, max_init, dist_converge_iter, init_val_try_dist));
    return rcpp_result_gen;
END_RCPP
}
// MMCLRpval_fun
double MMCLRpval_fun(arma::vec theta, List mdl_h0, List mdl_h1, bool msmu, bool msvar, int ar, int N, int maxit, double thtol, int burnin, bool stationary_ind, double lambda, int max_init, int dist_converge_iter, int init_val_try_dist, int workers);
RcppExport SEXP _MSTest_MMCLRpval_fun(SEXP thetaSEXP, SEXP mdl_h0SEXP, SEXP mdl_h1SEXP, SEXP msmuSEXP, SEXP msvarSEXP, SEXP arSEXP, SEXP NSEXP, SEXP maxitSEXP, SEXP thtolSEXP, SEXP burninSEXP, SEXP stationary_indSEXP, SEXP lambdaSEXP, SEXP max_initSEXP, SEXP dist_converge_iterSEXP, SEXP init_val_try_distSEXP, SEXP workersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl_h0(mdl_h0SEXP);
    Rcpp::traits::input_parameter< List >::type mdl_h1(mdl_h1SEXP);
    Rcpp::traits::input_parameter< bool >::type msmu(msmuSEXP);
    Rcpp::traits::input_parameter< bool >::type msvar(msvarSEXP);
    Rcpp::traits::input_parameter< int >::type ar(arSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type thtol(thtolSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< bool >::type stationary_ind(stationary_indSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_init(max_initSEXP);
    Rcpp::traits::input_parameter< int >::type dist_converge_iter(dist_converge_iterSEXP);
    Rcpp::traits::input_parameter< int >::type init_val_try_dist(init_val_try_distSEXP);
    Rcpp::traits::input_parameter< int >::type workers(workersSEXP);
    rcpp_result_gen = Rcpp::wrap(MMCLRpval_fun(theta, mdl_h0, mdl_h1, msmu, msvar, ar, N, maxit, thtol, burnin, stationary_ind, lambda, max_init, dist_converge_iter, init_val_try_dist, workers));
    return rcpp_result_gen;
END_RCPP
}
// MMCLRpval_fun_max
double MMCLRpval_fun_max(arma::vec theta, List mdl_h0, List mdl_h1, bool msmu, bool msvar, int ar, int N, int maxit, double thtol, int burnin, bool stationary_ind, double lambda, int max_init, int dist_converge_iter, int init_val_try_dist, int workers);
RcppExport SEXP _MSTest_MMCLRpval_fun_max(SEXP thetaSEXP, SEXP mdl_h0SEXP, SEXP mdl_h1SEXP, SEXP msmuSEXP, SEXP msvarSEXP, SEXP arSEXP, SEXP NSEXP, SEXP maxitSEXP, SEXP thtolSEXP, SEXP burninSEXP, SEXP stationary_indSEXP, SEXP lambdaSEXP, SEXP max_initSEXP, SEXP dist_converge_iterSEXP, SEXP init_val_try_distSEXP, SEXP workersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl_h0(mdl_h0SEXP);
    Rcpp::traits::input_parameter< List >::type mdl_h1(mdl_h1SEXP);
    Rcpp::traits::input_parameter< bool >::type msmu(msmuSEXP);
    Rcpp::traits::input_parameter< bool >::type msvar(msvarSEXP);
    Rcpp::traits::input_parameter< int >::type ar(arSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type thtol(thtolSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< bool >::type stationary_ind(stationary_indSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_init(max_initSEXP);
    Rcpp::traits::input_parameter< int >::type dist_converge_iter(dist_converge_iterSEXP);
    Rcpp::traits::input_parameter< int >::type init_val_try_dist(init_val_try_distSEXP);
    Rcpp::traits::input_parameter< int >::type workers(workersSEXP);
    rcpp_result_gen = Rcpp::wrap(MMCLRpval_fun_max(theta, mdl_h0, mdl_h1, msmu, msvar, ar, N, maxit, thtol, burnin, stationary_ind, lambda, max_init, dist_converge_iter, init_val_try_dist, workers));
    return rcpp_result_gen;
END_RCPP
}
// calc_DLmoments
arma::vec calc_DLmoments(arma::vec ehat);
RcppExport SEXP _MSTest_calc_DLmoments(SEXP ehatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type ehat(ehatSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_DLmoments(ehat));
    return rcpp_result_gen;
END_RCPP
}
// sim_DLmoments
arma::mat sim_DLmoments(int Tsize, int N);
RcppExport SEXP _MSTest_sim_DLmoments(SEXP TsizeSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Tsize(TsizeSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_DLmoments(Tsize, N));
    return rcpp_result_gen;
END_RCPP
}
// combine_stat
arma::vec combine_stat(arma::vec s0, arma::mat sN, arma::mat params, std::string type);
RcppExport SEXP _MSTest_combine_stat(SEXP s0SEXP, SEXP sNSEXP, SEXP paramsSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type s0(s0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sN(sNSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(combine_stat(s0, sN, params, type));
    return rcpp_result_gen;
END_RCPP
}
// calc_DLmcstat
arma::vec calc_DLmcstat(arma::vec ezt, int N, arma::mat params, Rcpp::String type);
RcppExport SEXP _MSTest_calc_DLmcstat(SEXP eztSEXP, SEXP NSEXP, SEXP paramsSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type ezt(eztSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_DLmcstat(ezt, N, params, type));
    return rcpp_result_gen;
END_RCPP
}
// approx_dist_loop
arma::mat approx_dist_loop(arma::mat SN2);
RcppExport SEXP _MSTest_approx_dist_loop(SEXP SN2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type SN2(SN2SEXP);
    rcpp_result_gen = Rcpp::wrap(approx_dist_loop(SN2));
    return rcpp_result_gen;
END_RCPP
}
// DLMMCpval_fun
double DLMMCpval_fun(arma::vec theta, arma::vec y, arma::mat x, int N, int simdist_N, Rcpp::String pval_type, bool stationary_ind, double lambda);
RcppExport SEXP _MSTest_DLMMCpval_fun(SEXP thetaSEXP, SEXP ySEXP, SEXP xSEXP, SEXP NSEXP, SEXP simdist_NSEXP, SEXP pval_typeSEXP, SEXP stationary_indSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type simdist_N(simdist_NSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type pval_type(pval_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type stationary_ind(stationary_indSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(DLMMCpval_fun(theta, y, x, N, simdist_N, pval_type, stationary_ind, lambda));
    return rcpp_result_gen;
END_RCPP
}
// DLMMCpval_fun_max
double DLMMCpval_fun_max(arma::vec theta, arma::vec y, arma::mat x, int N, int simdist_N, Rcpp::String pval_type, bool stationary_ind, double lambda);
RcppExport SEXP _MSTest_DLMMCpval_fun_max(SEXP thetaSEXP, SEXP ySEXP, SEXP xSEXP, SEXP NSEXP, SEXP simdist_NSEXP, SEXP pval_typeSEXP, SEXP stationary_indSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type simdist_N(simdist_NSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type pval_type(pval_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type stationary_ind(stationary_indSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(DLMMCpval_fun_max(theta, y, x, N, simdist_N, pval_type, stationary_ind, lambda));
    return rcpp_result_gen;
END_RCPP
}
// AR_loglik_fun
double AR_loglik_fun(arma::vec theta, List mdl);
RcppExport SEXP _MSTest_AR_loglik_fun(SEXP thetaSEXP, SEXP mdlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    rcpp_result_gen = Rcpp::wrap(AR_loglik_fun(theta, mdl));
    return rcpp_result_gen;
END_RCPP
}
// ARmdl_cpp
List ARmdl_cpp(arma::vec Y, int ar, bool intercept, bool getSE);
RcppExport SEXP _MSTest_ARmdl_cpp(SEXP YSEXP, SEXP arSEXP, SEXP interceptSEXP, SEXP getSESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type ar(arSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< bool >::type getSE(getSESEXP);
    rcpp_result_gen = Rcpp::wrap(ARmdl_cpp(Y, ar, intercept, getSE));
    return rcpp_result_gen;
END_RCPP
}
// VAR_loglik_fun
double VAR_loglik_fun(arma::vec theta, List mdl);
RcppExport SEXP _MSTest_VAR_loglik_fun(SEXP thetaSEXP, SEXP mdlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    rcpp_result_gen = Rcpp::wrap(VAR_loglik_fun(theta, mdl));
    return rcpp_result_gen;
END_RCPP
}
// VARmdl
List VARmdl(arma::mat Y, int ar, bool intercept, bool getSE);
RcppExport SEXP _MSTest_VARmdl(SEXP YSEXP, SEXP arSEXP, SEXP interceptSEXP, SEXP getSESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type ar(arSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< bool >::type getSE(getSESEXP);
    rcpp_result_gen = Rcpp::wrap(VARmdl(Y, ar, intercept, getSE));
    return rcpp_result_gen;
END_RCPP
}
// MSloglik_fun
double MSloglik_fun(arma::vec theta, List mdl, int k);
RcppExport SEXP _MSTest_MSloglik_fun(SEXP thetaSEXP, SEXP mdlSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(MSloglik_fun(theta, mdl, k));
    return rcpp_result_gen;
END_RCPP
}
// MSloglik_fun_min
double MSloglik_fun_min(arma::vec theta, List mdl, int k);
RcppExport SEXP _MSTest_MSloglik_fun_min(SEXP thetaSEXP, SEXP mdlSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(MSloglik_fun_min(theta, mdl, k));
    return rcpp_result_gen;
END_RCPP
}
// MSloglik
List MSloglik(arma::vec theta, List mdl, int k);
RcppExport SEXP _MSTest_MSloglik(SEXP thetaSEXP, SEXP mdlSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(MSloglik(theta, mdl, k));
    return rcpp_result_gen;
END_RCPP
}
// MSVARloglik_fun
double MSVARloglik_fun(arma::vec theta, List mdl, int k);
RcppExport SEXP _MSTest_MSVARloglik_fun(SEXP thetaSEXP, SEXP mdlSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(MSVARloglik_fun(theta, mdl, k));
    return rcpp_result_gen;
END_RCPP
}
// MSVARloglik_fun_min
double MSVARloglik_fun_min(arma::vec theta, List mdl, int k);
RcppExport SEXP _MSTest_MSVARloglik_fun_min(SEXP thetaSEXP, SEXP mdlSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(MSVARloglik_fun_min(theta, mdl, k));
    return rcpp_result_gen;
END_RCPP
}
// MSVARloglik
List MSVARloglik(arma::vec theta, List mdl, int k);
RcppExport SEXP _MSTest_MSVARloglik(SEXP thetaSEXP, SEXP mdlSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(MSVARloglik(theta, mdl, k));
    return rcpp_result_gen;
END_RCPP
}
// MS_EMaximization
List MS_EMaximization(arma::vec theta, List mdl, List MSloglik_output, int k);
RcppExport SEXP _MSTest_MS_EMaximization(SEXP thetaSEXP, SEXP mdlSEXP, SEXP MSloglik_outputSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< List >::type MSloglik_output(MSloglik_outputSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(MS_EMaximization(theta, mdl, MSloglik_output, k));
    return rcpp_result_gen;
END_RCPP
}
// MSVAR_EMaximization
List MSVAR_EMaximization(arma::vec theta, List mdl, List MSloglik_output, int k);
RcppExport SEXP _MSTest_MSVAR_EMaximization(SEXP thetaSEXP, SEXP mdlSEXP, SEXP MSloglik_outputSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< List >::type MSloglik_output(MSloglik_outputSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(MSVAR_EMaximization(theta, mdl, MSloglik_output, k));
    return rcpp_result_gen;
END_RCPP
}
// MS_EMiter
List MS_EMiter(List mdl, List EMest_output, int k);
RcppExport SEXP _MSTest_MS_EMiter(SEXP mdlSEXP, SEXP EMest_outputSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< List >::type EMest_output(EMest_outputSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(MS_EMiter(mdl, EMest_output, k));
    return rcpp_result_gen;
END_RCPP
}
// MSVAR_EMiter
List MSVAR_EMiter(List mdl, List EMest_output, int k);
RcppExport SEXP _MSTest_MSVAR_EMiter(SEXP mdlSEXP, SEXP EMest_outputSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< List >::type EMest_output(EMest_outputSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(MSVAR_EMiter(mdl, EMest_output, k));
    return rcpp_result_gen;
END_RCPP
}
// MS_EMest
List MS_EMest(arma::vec theta_0, List mdl, int k, List optim_options);
RcppExport SEXP _MSTest_MS_EMest(SEXP theta_0SEXP, SEXP mdlSEXP, SEXP kSEXP, SEXP optim_optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta_0(theta_0SEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< List >::type optim_options(optim_optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(MS_EMest(theta_0, mdl, k, optim_options));
    return rcpp_result_gen;
END_RCPP
}
// MSVAR_EMest
List MSVAR_EMest(arma::vec theta_0, List mdl, int k, List optim_options);
RcppExport SEXP _MSTest_MSVAR_EMest(SEXP theta_0SEXP, SEXP mdlSEXP, SEXP kSEXP, SEXP optim_optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta_0(theta_0SEXP);
    Rcpp::traits::input_parameter< List >::type mdl(mdlSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< List >::type optim_options(optim_optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(MSVAR_EMest(theta_0, mdl, k, optim_options));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MSTest_cov2corr", (DL_FUNC) &_MSTest_cov2corr, 1},
    {"_MSTest_covar_vech", (DL_FUNC) &_MSTest_covar_vech, 1},
    {"_MSTest_covar_unvech", (DL_FUNC) &_MSTest_covar_unvech, 2},
    {"_MSTest_logLike_AR", (DL_FUNC) &_MSTest_logLike_AR, 2},
    {"_MSTest_logLike_VAR", (DL_FUNC) &_MSTest_logLike_VAR, 2},
    {"_MSTest_randP", (DL_FUNC) &_MSTest_randP, 1},
    {"_MSTest_limP", (DL_FUNC) &_MSTest_limP, 1},
    {"_MSTest_ts_lagged", (DL_FUNC) &_MSTest_ts_lagged, 2},
    {"_MSTest_paramListMS", (DL_FUNC) &_MSTest_paramListMS, 5},
    {"_MSTest_paramListMSVAR", (DL_FUNC) &_MSTest_paramListMSVAR, 6},
    {"_MSTest_calcMSResid", (DL_FUNC) &_MSTest_calcMSResid, 3},
    {"_MSTest_calcMSVARResid", (DL_FUNC) &_MSTest_calcMSVARResid, 3},
    {"_MSTest_initValsMS", (DL_FUNC) &_MSTest_initValsMS, 2},
    {"_MSTest_initValsMSVAR", (DL_FUNC) &_MSTest_initValsMSVAR, 2},
    {"_MSTest_MCpval", (DL_FUNC) &_MSTest_MCpval, 3},
    {"_MSTest_simuAR", (DL_FUNC) &_MSTest_simuAR, 2},
    {"_MSTest_simuMSAR", (DL_FUNC) &_MSTest_simuMSAR, 2},
    {"_MSTest_simuVAR", (DL_FUNC) &_MSTest_simuVAR, 2},
    {"_MSTest_simuMSVAR", (DL_FUNC) &_MSTest_simuMSVAR, 2},
    {"_MSTest_simuNorm", (DL_FUNC) &_MSTest_simuNorm, 1},
    {"_MSTest_simuHMM", (DL_FUNC) &_MSTest_simuHMM, 2},
    {"_MSTest_calc_mu2t_mv", (DL_FUNC) &_MSTest_calc_mu2t_mv, 4},
    {"_MSTest_calc_mu2t", (DL_FUNC) &_MSTest_calc_mu2t, 3},
    {"_MSTest_chpStat", (DL_FUNC) &_MSTest_chpStat, 4},
    {"_MSTest_bootCV", (DL_FUNC) &_MSTest_bootCV, 4},
    {"_MSTest_LR_samp_dist", (DL_FUNC) &_MSTest_LR_samp_dist, 11},
    {"_MSTest_MMCLRpval_fun", (DL_FUNC) &_MSTest_MMCLRpval_fun, 16},
    {"_MSTest_MMCLRpval_fun_max", (DL_FUNC) &_MSTest_MMCLRpval_fun_max, 16},
    {"_MSTest_calc_DLmoments", (DL_FUNC) &_MSTest_calc_DLmoments, 1},
    {"_MSTest_sim_DLmoments", (DL_FUNC) &_MSTest_sim_DLmoments, 2},
    {"_MSTest_combine_stat", (DL_FUNC) &_MSTest_combine_stat, 4},
    {"_MSTest_calc_DLmcstat", (DL_FUNC) &_MSTest_calc_DLmcstat, 4},
    {"_MSTest_approx_dist_loop", (DL_FUNC) &_MSTest_approx_dist_loop, 1},
    {"_MSTest_DLMMCpval_fun", (DL_FUNC) &_MSTest_DLMMCpval_fun, 8},
    {"_MSTest_DLMMCpval_fun_max", (DL_FUNC) &_MSTest_DLMMCpval_fun_max, 8},
    {"_MSTest_AR_loglik_fun", (DL_FUNC) &_MSTest_AR_loglik_fun, 2},
    {"_MSTest_ARmdl_cpp", (DL_FUNC) &_MSTest_ARmdl_cpp, 4},
    {"_MSTest_VAR_loglik_fun", (DL_FUNC) &_MSTest_VAR_loglik_fun, 2},
    {"_MSTest_VARmdl", (DL_FUNC) &_MSTest_VARmdl, 4},
    {"_MSTest_MSloglik_fun", (DL_FUNC) &_MSTest_MSloglik_fun, 3},
    {"_MSTest_MSloglik_fun_min", (DL_FUNC) &_MSTest_MSloglik_fun_min, 3},
    {"_MSTest_MSloglik", (DL_FUNC) &_MSTest_MSloglik, 3},
    {"_MSTest_MSVARloglik_fun", (DL_FUNC) &_MSTest_MSVARloglik_fun, 3},
    {"_MSTest_MSVARloglik_fun_min", (DL_FUNC) &_MSTest_MSVARloglik_fun_min, 3},
    {"_MSTest_MSVARloglik", (DL_FUNC) &_MSTest_MSVARloglik, 3},
    {"_MSTest_MS_EMaximization", (DL_FUNC) &_MSTest_MS_EMaximization, 4},
    {"_MSTest_MSVAR_EMaximization", (DL_FUNC) &_MSTest_MSVAR_EMaximization, 4},
    {"_MSTest_MS_EMiter", (DL_FUNC) &_MSTest_MS_EMiter, 3},
    {"_MSTest_MSVAR_EMiter", (DL_FUNC) &_MSTest_MSVAR_EMiter, 3},
    {"_MSTest_MS_EMest", (DL_FUNC) &_MSTest_MS_EMest, 4},
    {"_MSTest_MSVAR_EMest", (DL_FUNC) &_MSTest_MSVAR_EMest, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_MSTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
