# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_mu2t_mv <- function(mdl, rho, ltmt, hv) {
    .Call(`_MSTest_calc_mu2t_mv`, mdl, rho, ltmt, hv)
}

calc_mu2t <- function(mdl, rho, ltmt) {
    .Call(`_MSTest_calc_mu2t`, mdl, rho, ltmt)
}

#' @title CHP Test Statistic
#'
#' @param mdl List containing model information
#' @param rho_b bound for rho (nuisance param space)
#' @param ltmt List containing  relevant first and second derivatives of log likelihood function.
#' @param var_switch variance switch indicator
#' 
#' @return Test Statistic
#' @export
chpStat <- function(mdl, rho_b, ltmt, var_switch) {
    .Call(`_MSTest_chpStat`, mdl, rho_b, ltmt, var_switch)
}

#' @title Bootstrap Critival Values CHP Test
#'
#' @param mdl List containing model information
#' @param rho_b bound for rho (nuisance param space)
#' @param N number of simulations
#' @param var_switch variance switch indicator
#' 
#' @return Bootstrap critical values
#' @export
bootCV <- function(mdl, rho_b, N, var_switch) {
    .Call(`_MSTest_bootCV`, mdl, rho_b, N, var_switch)
}

CHPadist <- function(itn, tr, rho_b) {
    .Call(`_MSTest_CHPadist`, itn, tr, rho_b)
}

calc_moments <- function(ehat) {
    .Call(`_MSTest_calc_moments`, ehat)
}

sim_moments <- function(t, totsim) {
    .Call(`_MSTest_sim_moments`, t, totsim)
}

combine_stat <- function(s0, sN, params, N, type) {
    .Call(`_MSTest_combine_stat`, s0, sN, params, N, type)
}

calc_mcstat <- function(ezt, N, params) {
    .Call(`_MSTest_calc_mcstat`, ezt, N, params)
}

approx_dist_loop <- function(SN2) {
    .Call(`_MSTest_approx_dist_loop`, SN2)
}

grid_eval <- function(y, x, mcgrid, N, params) {
    .Call(`_MSTest_grid_eval`, y, x, mcgrid, N, params)
}

transMat_cpp <- function(ind, k) {
    .Call(`_MSTest_transMat_cpp`, ind, k)
}

randInitVal_cpp <- function(mdl, k) {
    .Call(`_MSTest_randInitVal_cpp`, mdl, k)
}

ms_logLikel_cpp <- function(th, y, X, MScoef) {
    .Call(`_MSTest_ms_logLikel_cpp`, th, y, X, MScoef)
}

EM_hamilton_cpp <- function(th, y, X, MScoef, vof) {
    .Call(`_MSTest_EM_hamilton_cpp`, th, y, X, MScoef, vof)
}

msmdl_cpp <- function(mdl, k, method = "eval", mxit = 500L) {
    .Call(`_MSTest_msmdl_cpp`, mdl, k, method, mxit)
}

