# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calc eq. 2.5 from CHP (2014) where both mean and variance can switch
#'
#' When alternative has bith switching mean and variance, we take the second 
#' derivative of the log likelihood function w.r.t mu, phi and sigma.
#' 
#' Output from this function is used as input in \emph{chpStat}
#'
#' @param mdl List containing model information
#' @param rho_b bound for rho (nuisance param space)
#' @param ltmt List conatining derivatives (i.e. is the output when using \emph{chpDmat})
#' 
#' @return mu_2t from eq. 2.5 and used in test-statistic caluclation
#' 
#' @references Carrasco, Marine, Liang Hu, and Werner Ploberger. 2014. 
#' “Optimal test for Markov switch- ing parameters.” \emph{Econometrica} \bold{82 (2)}: 765–784.
#' 
#' @export
calc_mu2t_mv <- function(mdl, rho, ltmt, hv) {
    .Call(`_MSTest_calc_mu2t_mv`, mdl, rho, ltmt, hv)
}

#' @title Calc eq. 2.5 from CHP (2014) where only mean can switch
#'
#' When alternative only has Switching mean (and not variance), we only take the second 
#' derivative of the log likelihood function w.r.t mu and not phi or sigma.
#' 
#' Output from this function is used as input in \emph{chpStat}
#'
#' @param mdl List containing model information
#' @param rho_b bound for rho (nuisance param space)
#' @param ltmt List conatining derivatives (i.e. is the output when using \emph{chpDmat})
#' 
#' @return mu_2t from eq. 2.5 and used in test-statistic caluclation
#' 
#' @references Carrasco, Marine, Liang Hu, and Werner Ploberger. 2014. 
#' “Optimal test for Markov switch- ing parameters.” \emph{Econometrica} \bold{82 (2)}: 765–784.
#' @export
calc_mu2t <- function(mdl, rho, ltmt) {
    .Call(`_MSTest_calc_mu2t`, mdl, rho, ltmt)
}

#' @title CHP Test Statistic
#' 
#' Calculate supTS and expTS test-statistics from CHP (2014).
#'
#' @param mdl List containing model information
#' @param rho_b bound for rho (nuisance param space)
#' @param ltmt List containing  relevant first and second derivatives of log likelihood function.
#' @param var_switch variance switch indicator
#' 
#' @return Test Statistic
#' 
#' @references Carrasco, Marine, Liang Hu, and Werner Ploberger. 2014. 
#' “Optimal test for Markov switch- ing parameters.” \emph{Econometrica} \bold{82 (2)}: 765–784.
#' 
#' @export
chpStat <- function(mdl, rho_b, ltmt, var_switch) {
    .Call(`_MSTest_chpStat`, mdl, rho_b, ltmt, var_switch)
}

#' @title Bootstrap Critival Values CHP Test
#'
#'This bootstrap procedure is described on page 771 of CHP (2014)
#'
#' @param mdl List containing model information
#' @param rho_b bound for rho (nuisance param space)
#' @param N number of simulations
#' @param var_switch variance switch indicator
#' 
#' @return Bootstrap critical values
#' 
#' @references Carrasco, Marine, Liang Hu, and Werner Ploberger. 2014. 
#' “Optimal test for Markov switch- ing parameters.” \emph{Econometrica} \bold{82 (2)}: 765–784.
#' 
#' @export
bootCV <- function(mdl, rho_b, N, var_switch) {
    .Call(`_MSTest_bootCV`, mdl, rho_b, N, var_switch)
}

#' @title Asymptotic Distribution of Test Statistic
#' 
#' Can be used for hypothesis test using asymptotic critical values. Doing so is much 
#' quicker than using empirical distribution. Results should also be comparable to Table A1
#' in CHP (2014).
#' 
#' @param itn number of bootstrap iterations 
#' @param tr sample size of each series
#' @param rho_b 
#' 
#' @return asymptotic distribution of test statistics
#' @export
CHPadist <- function(itn, tr, rho_b) {
    .Call(`_MSTest_CHPadist`, itn, tr, rho_b)
}

#' @title Calculate Moment-based test-statistics 
#'
#' This function computes the four momment-based test-statistics (eq. 11 - 14 in paper) 
#' for a given series. The series should be the residuals from an AR model. 
#' 
#'
#' @param ehat vector containing series of residuals from model.
#' 
#' @return The four test statistics (eq. 11 - 14 in paper)
#' 
#' @references Dufour, J. M., & Luger, R. (2017). Identification-robust moment-based 
#' tests for Markov switching in autoregressive models. Econometric Reviews, 36(6-9), 713-727.
#' 
#' @export
calc_moments <- function(ehat) {
    .Call(`_MSTest_calc_moments`, ehat)
}

#' @title Test-statistics from simulated data
#'
#' This function computes simulates residuals from a standard normal distribution
#' and calculates the four momment-based test-statistics (eq. 11 - 14 in paper) under the 
#' null hypothesis using this simulated data.
#' 
#' @param t length of sample size for simulation 
#' @param number of simulated samples
#' 
#' @return The four test statistics (eq. 11 - 14 in paper)
#' 
#' @references Dufour, J. M., & Luger, R. (2017). Identification-robust moment-based 
#' tests for Markov switching in autoregressive models. Econometric Reviews, 36(6-9), 713-727.
#' 
#' @export
sim_moments <- function(t, totsim) {
    .Call(`_MSTest_sim_moments`, t, totsim)
}

#' @title Combine p-values 
#'
#' This function is used to combine the p-values as in eq 17 and 18 of Dufour & Luger (2017).
#' The input parameter \emph{type} can be used to used to specify the method for combining 
#' the pvalues. If set to "min" the min method of combining p-values is used as in Fisher (1932) 
#' and Pearson (1933). If set to "prod" the product of p-values is used as in Tippett (1931) 
#' and Wilkinson (1951).
#' 
#' @param s0 test-statistic under the alternative
#' @param sN test-statistics under the null
#' @param param output from \emph{approxDist} which obtains the parameters needed in eq. 16 which is used for 
#' combining p-values.
#' @param N total number of test statistics (i.e. simulated + observed = N)
#' @param type the type of method used to combine p-values. If set to "min" the min method of combining p-values is used as in Fisher (1932) 
#' and Pearson (1933). If set to "prod" the product of p-values is used as in Tippett (1931) 
#' and Wilkinson (1951).
#' 
#' @return The four test statistics (eq. 11 - 14 in paper)
#' 
#' @references Dufour, J. M., & Luger, R. (2017). Identification-robust moment-based 
#' tests for Markov switching in autoregressive models. Econometric Reviews, 36(6-9), 713-727.
#' @references Tippett, L. (1931). The Method of Statistics. London: Williams & Norgate.
#' @references Wilkinson, B. (1951). A statistical consideration in psychological research. 
#' Psychology Bulletin 48:156–158.
#' @references Pearson, K. (1933). On a method of determining whether a sample of size n
#'  supposed to have been drawn from a parent population having a known probability integral has probably been drawn at random. Biometrika 25:379–410.
#' @references Fisher, R. (1932). Statistical Methods for Research Workers. Edinburgh: 
#' Oliver and Boyd.
#' 
#' @export
combine_stat <- function(s0, sN, params, N, type) {
    .Call(`_MSTest_combine_stat`, s0, sN, params, N, type)
}

#' @title Calculate combined p-value test statistic 
#'
#' This function computes test-statistics for observed and simulated samples. 
#' It begins by calculating it for the obsted data, then generates test-statistics from 
#' simulated data to approximate null distribution and then calculates the p-values and 
#' combines them according to eq. 17 or 18 of Dufour & Luger (2017).
#' 
#' @param ezt observed series
#' @param N total number of test statistics (i.e. simulated + observed = N)
#' @param param output from \emph{approxDist} which obtains the parameters needed in eq. 16 which is used for 
#' combining p-values.
#' 
#' @return The four test statistics (eq. 11 - 14 in paper)
#' 
#' @references Dufour, J. M., & Luger, R. (2017). Identification-robust moment-based 
#' tests for Markov switching in autoregressive models. Econometric Reviews, 36(6-9), 713-727.
#' 
#' @export
calc_mcstat <- function(ezt, N, params) {
    .Call(`_MSTest_calc_mcstat`, ezt, N, params)
}

#' @title Loop for \emph{approxDist}
#'
#' This function performs the loop in \emph{approxDist}. It is written in C++ for better 
#' performance in terms of speed.
#' 
#' @param SN2 matrix of Tx4 test-statistics
#' 
#' @return The four test statistics from smulated data in [0,1]. Used for NLS to get 
#' params needed to combine p-values
#' 
#' @references Dufour, J. M., & Luger, R. (2017). Identification-robust moment-based 
#' tests for Markov switching in autoregressive models. Econometric Reviews, 36(6-9), 713-727.
#' 
#' @export    
approx_dist_loop <- function(SN2) {
    .Call(`_MSTest_approx_dist_loop`, SN2)
}

#' @title Evaluate Grid for GridSearch optimization. 
#'
#' This function performs the gridsearch loop over nuisance parameter space in 
#' \emph{calc_mmcpval}. It is written in C++ for better  performance in terms of speed.
#' It is only used when calling gridSearch_paramCI or randSearch_paramCI as optimization 
#' method.
#' 
#' @param ext observed series
#' @param N total number of test statistics (i.e. simulated + observed = N)
#' 
#' @return maximized p-value over parameter space.
#' 
#' @references Dufour, J. M., & Luger, R. (2017). Identification-robust moment-based 
#' tests for Markov switching in autoregressive models. Econometric Reviews, 36(6-9), 713-727.
#' 
#' @export
grid_eval <- function(y, x, mcgrid, N, params) {
    .Call(`_MSTest_grid_eval`, y, x, mcgrid, N, params)
}

transMat_cpp <- function(ind, k) {
    .Call(`_MSTest_transMat_cpp`, ind, k)
}

randInitVal_cpp <- function(mdl, k) {
    .Call(`_MSTest_randInitVal_cpp`, mdl, k)
}

ms_logLikel_cpp <- function(th, y, X, MScoef) {
    .Call(`_MSTest_ms_logLikel_cpp`, th, y, X, MScoef)
}

EM_hamilton_cpp <- function(th, y, X, MScoef, vof) {
    .Call(`_MSTest_EM_hamilton_cpp`, th, y, X, MScoef, vof)
}

msmdl_cpp <- function(mdl, k, method = "eval", mxit = 500L) {
    .Call(`_MSTest_msmdl_cpp`, mdl, k, method, mxit)
}

